### ISSUE TITLE
Indentation Broken in Hamlet

### ISSUE THREAD

**Issue by AshtonKem** [CodyReichert/shakespeare-mode#11]
It seems that I cannot convince shakespeare mode that any line should be on the same line as its predecessor. This of course makes it pretty much impossible to write shakespeare templates.

**Comment by CodyReichert** [comment]
Hey @AshtonKem, thanks for the report. I haven't quite had time to investigate this yet, but there is another issue ( #7 ) that may be related (?). I'm not sure if there's a workaround yet, but hopefully with enough collaboration we can get it fixed.

**Comment by CodyReichert** [comment]
Hey @AshtonKem, a PR was just merged that should hopefully fix this and add some new indentation functions as well.

I'll close this, but feel free to re-open if you hit any changes on the latest version.
