### ISSUE TITLE
shakespeare-mode hangs when pressing "o" on first line

### ISSUE THREAD

**Issue by chkl** [CodyReichert/shakespeare-mode#13]
First of all, I want to thank you for working on shakespeare-mode. It makes working with templates a lot more pleasurable!

I found a small bug though. In Spacemacs, when I'm on the first line (and only then) pressing "o" (to start a newline above) makes Emacs hang. It's not a huge deal and I don't know much about the inner workings of emacs (if so, I'd try to fix it myself), but I thought I'd let you know.

**Comment by CodyReichert** [comment]
Hey, thanks for the report! That's interesting. I don't use spacemacs myself, but might be able to get it running and see what happens.

Actually, would you be able to try this? https://github.com/syl20bnr/spacemacs/wiki/Debugging#debug-a-freezing-instance

That might help us figure out what's going on and if it's anything specific to your system/version. Just post the output, or if not let me know and I'll try to check it!

**Comment by CodyReichert** [comment]
That's perfect, thanks @chkl! I was able to reproduce it here locally (without spacemacs), and it is indeed an issue with trying to calculate the indent level on the first line. Really odd no one's hit this before.

I'm playing with a few changes locally and will try to get u p a fix asap!

**Comment by chkl** [comment]
Sounds great. Thank you very much:-)

**Comment by CodyReichert** [comment]
Hey @chkl - alright I just pushed up a fix, hopefully, for this one here: https://github.com/CodyReichert/shakespeare-mode/commit/c442eeea9d585e1b1fbb8813e33d47feec348a57 Probably bigger than it has to be, but it guards against a couple similar cases.

Re-open this if you're still having any issues after updating the package (from melpa or wherever), or if you have any other issues! Thanks again - Cody

**Comment by CodyReichert** [comment]
Also tagged `v0.0.2` in case you're using melpa-stable (might take a second to show up on both of those).
