### ISSUE TITLE
Provide releases for melpa-stable

### ISSUE THREAD

**Issue by the-kenny** [CodyReichert/shakespeare-mode#8]
Melpa unfortunately only contains nightly builds. People don't want nightly builds to break their editor.

http://stable.melpa.org/ uses the same set of packages as Melpa, but only builds tagged releases. It would be really nice if you could tag a current release so it shows up in melpa-table.

**Comment by CodyReichert** [comment]
All I have to do is tag a release? That's easy. [Just tagged it](https://github.com/CodyReichert/shakespeare-mode/releases/tag/v0.0.1) - I'll wait for it to show up and then close this issue.

Thanks!

**Comment by CodyReichert** [comment]
It looks like I did everything correctly:

http://stable.melpa.org/#/shakespeare-mode

Please re-open if it's not working or I missed a step - thanks again!

**Comment by the-kenny** [comment]
It's perfect, thank you!
