### ISSUE TITLE
Indentation functions for hamlet-mode

### ISSUE THREAD

**Issue by tsukimizake** [CodyReichert/shakespeare-mode#9]
Hello. I tried to write indentation functions for shakespeare-hamlet-mode.
https://github.com/tsukimizake/shakespeare-mode
What do you think of it? May I send a pull-request?

**Comment by CodyReichert** [comment]
Hey @tsukimizake, I'm sorry for such a late reply to this.

 I haven't had a chance to test the indentation functions yet, but definitely feel free to submit a PR! I can give it a whirl and I don't mind merging it if it's all good.

Just a side thought, I would like to get #11 and #7 fixed up before changing any of the indentation, but maybe this is also a possible fix?

**Comment by tsukimizake** [comment]
Thanks. Here's the PR. If you find something curious, please feel free to ask me.
#12

> Just a side thought, I would like to get #11 and #7 fixed up before changing any of the indentation, but maybe this is also a possible fix?

Yes, I think they'll be satisfied with it. 
Actually, I encountered the same as #7, and I wrote this to fix the issue.

**Comment by agrafix** [comment]
Nice! Looking forward to this PR being merged as I see the same issue.

**Comment by CodyReichert** [comment]
I just merged this PR - should be up on MELPA within an hour or so.

If there are any problems please feel free to re-open the issue.

And thanks again @tsukimizake, it works great!
